name: kraya
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  build_runner: ^2.2.0
  dartz: ^0.10.1
  drop_shadow: ^0.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  cached_network_image: ^3.2.3
  http: ^0.13.5
  google_fonts: ^4.0.4
  mockito: ^5.3.0
  pinput: ^2.2.31
  material_design_icons_flutter: ^7.0.7296
  carousel_slider: ^4.2.1
  expandable: ^5.0.1
  animated_bottom_navigation_bar: ^1.1.0+1
  flutter_rating_bar: ^4.0.1
  collection: ^1.15.0
  image_picker: ^0.8.7+4
  permission_handler: ^10.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true


  assets:
    - images/
flutter_intl:
  enabled: true