name: kraya
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.1.0+1
  build_runner: ^2.2.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  collection: ^1.15.0
  dartz: ^0.10.1
  drop_shadow: ^0.1.0
  equatable: ^2.0.5
  expandable: ^5.0.1
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_rating_bar: ^4.0.1
  get_it: ^7.6.0
  go_router: ^8.0.1
  google_fonts: ^4.0.4
  http: ^0.13.5
  hydrated_bloc: ^9.1.1
  image_picker: ^0.8.7+4
  intl: ^0.18.1
  material_design_icons_flutter: ^7.0.7296
  mockito: ^5.3.0
  path_provider: ^2.0.15
  permission_handler: ^10.0.0
  pinput: ^2.2.31
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
