// Mocks generated by Mockito 5.3.2 from annotations
// in kraya_backend/features/core/registration/data/datasource/remote.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i5;

import 'package:kraya_backend/core/enum/enums.dart' as _i4;
import 'package:kraya_backend/features/core/registration/data/datasource/remote.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RegistrationRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegistrationRemoteDataSource extends _i1.Mock
    implements _i2.RegistrationRemoteDataSource {
  @override
  _i3.Future<String> submit({
    required String? firstName,
    required String? lastName,
    required String? phone,
    String? email,
    required DateTime? dateOfBirth,
    required _i4.Gender? gender,
    required _i4.Role? role,
    _i5.File? profilePicture,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submit,
          [],
          {
            #firstName: firstName,
            #lastName: lastName,
            #phone: phone,
            #email: email,
            #dateOfBirth: dateOfBirth,
            #gender: gender,
            #role: role,
            #profilePicture: profilePicture,
          },
        ),
        returnValue: _i3.Future<String>.value(''),
        returnValueForMissingStub: _i3.Future<String>.value(''),
      ) as _i3.Future<String>);
}
